In [2]:
import numpy as np

In [3]:
temparr = np.array([1,2,3])
temparr

array([1, 2, 3])

In [4]:
temparr2 = np.array([[1,2,3],[4,5,6]])
temparr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
temparr3 = np.array([[[1,2,3],[4,5,6],[1,4,7]],[[7,8,9],[1,3,5],[4,1,7]],[[2,4,6],[4,6,8],[3,7,2]]])
temparr3

array([[[1, 2, 3],
        [4, 5, 6],
        [1, 4, 7]],

       [[7, 8, 9],
        [1, 3, 5],
        [4, 1, 7]],

       [[2, 4, 6],
        [4, 6, 8],
        [3, 7, 2]]])

In [6]:
temparr.size, temparr.ndim, temparr.dtype, temparr.shape, type(temparr)

(3, 1, dtype('int32'), (3,), numpy.ndarray)

In [7]:
temparr2.size, temparr2.shape, temparr2.dtype, temparr2.ndim, type(temparr2)

(6, (2, 3), dtype('int32'), 2, numpy.ndarray)

In [8]:
temparr3.size, temparr3.shape, temparr3.dtype, temparr3.ndim, type(temparr3)

(27, (3, 3, 3), dtype('int32'), 3, numpy.ndarray)

In [9]:
temparr3.shape

(3, 3, 3)

In [10]:
import pandas as pd

In [11]:
datarr = pd.DataFrame(temparr)
datarr

0
0  1
1  2
2  3

In [12]:
np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
np.zeros((7,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
np.random.seed(0)
randarr = np.random.randint(100,size=(3))
randarr


array([44, 47, 64])

In [15]:
np.random.randint(1,size=(3,5)).astype(float)


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.random.seed(42)
randarr = np.random.randint(10,size=(3,7))
randarr

array([[6, 3, 7, 4, 6, 9, 2],
       [6, 7, 4, 3, 7, 7, 2],
       [5, 4, 1, 7, 5, 1, 4]])

In [17]:
unq = np.unique(randarr)

In [18]:
unq[0]

1

In [19]:
unq[:2]

array([1, 2])

In [22]:
rand1 = np.random.randint(10,size=(3,5))
rand2 = np.ones((3,5))
rand3 = rand1+rand2
rand3

array([[ 1.,  4.,  2.,  8.,  4.],
       [ 2.,  6.,  6., 10.,  4.],
       [ 6.,  2., 10.,  2., 10.]])

In [23]:
rand4 = np.ones((3,5))
rand3 = rand3-rand4
rand3

array([[0., 3., 1., 7., 3.],
       [1., 5., 5., 9., 3.],
       [5., 1., 9., 1., 9.]])

In [24]:
rand4*rand3

array([[0., 3., 1., 7., 3.],
       [1., 5., 5., 9., 3.],
       [5., 1., 9., 1., 9.]])

In [25]:
np.square(rand4*rand3)

array([[ 0.,  9.,  1., 49.,  9.],
       [ 1., 25., 25., 81.,  9.],
       [25.,  1., 81.,  1., 81.]])

In [27]:
np.sqrt(rand4*rand3).astype(int)

array([[0, 1, 1, 2, 1],
       [1, 2, 2, 3, 1],
       [2, 1, 3, 1, 3]])

In [31]:
np.mean(rand3)

4.133333333333334

In [30]:
np.max(rand3)

9.0

In [32]:
rand3.reshape((3,5,1))

array([[[0.],
        [3.],
        [1.],
        [7.],
        [3.]],

       [[1.],
        [5.],
        [5.],
        [9.],
        [3.]],

       [[5.],
        [1.],
        [9.],
        [1.],
        [9.]]])

In [33]:
rand3.T

array([[0., 1., 5.],
       [3., 5., 1.],
       [1., 5., 9.],
       [7., 9., 1.],
       [3., 3., 9.]])