In [25]:
from sklearn.datasets import fetch_olivetti_faces
faces = fetch_olivetti_faces()
faces

{'data': array([[0.30991736, 0.3677686 , 0.41735536, ..., 0.15289256, 0.16115703,
         0.1570248 ],
        [0.45454547, 0.47107437, 0.5123967 , ..., 0.15289256, 0.15289256,
         0.15289256],
        [0.3181818 , 0.40082645, 0.49173555, ..., 0.14049587, 0.14876033,
         0.15289256],
        ...,
        [0.5       , 0.53305787, 0.607438  , ..., 0.17768595, 0.14876033,
         0.19008264],
        [0.21487603, 0.21900827, 0.21900827, ..., 0.57438016, 0.59090906,
         0.60330576],
        [0.5165289 , 0.46280992, 0.28099173, ..., 0.35950413, 0.3553719 ,
         0.38429752]], dtype=float32),
 'images': array([[[0.30991736, 0.3677686 , 0.41735536, ..., 0.37190083,
          0.3305785 , 0.30578512],
         [0.3429752 , 0.40495867, 0.43801653, ..., 0.37190083,
          0.338843  , 0.3140496 ],
         [0.3429752 , 0.41735536, 0.45041323, ..., 0.38016528,
          0.338843  , 0.29752067],
         ...,
         [0.21487603, 0.20661157, 0.2231405 , ..., 0.15289256,
     

In [26]:
import pandas as pd
faces_df = pd.DataFrame(faces["data"])
faces_df["target"] = faces["target"]
faces_df

0         1         2         3         4         5         6  \
0    0.309917  0.367769  0.417355  0.442149  0.528926  0.607438  0.657025   
1    0.454545  0.471074  0.512397  0.557851  0.595041  0.640496  0.681818   
2    0.318182  0.400826  0.491736  0.528926  0.586777  0.657025  0.681818   
3    0.198347  0.194215  0.194215  0.194215  0.190083  0.190083  0.243802   
4    0.500000  0.545455  0.582645  0.623967  0.648760  0.690083  0.694215   
..        ...       ...       ...       ...       ...       ...       ...   
395  0.400826  0.495868  0.570248  0.632231  0.648760  0.640496  0.661157   
396  0.367769  0.367769  0.351240  0.301653  0.247934  0.247934  0.367769   
397  0.500000  0.533058  0.607438  0.628099  0.657025  0.632231  0.657025   
398  0.214876  0.219008  0.219008  0.223140  0.210744  0.202479  0.276859   
399  0.516529  0.462810  0.280992  0.252066  0.247934  0.367769  0.574380   

            7         8         9  ...      4087      4088      4089  \
0    0.677686  0.690083  0.685950  ...  0.669421  0.652893  0.661157   
1    0.702479  0.710744  0.702479  ...  0.157025  0.136364  0.148760   
2    0.685950  0.702479  0.698347  ...  0.132231  0.181818  0.136364   
3    0.404959  0.483471  0.516529  ...  0.636364  0.657025  0.685950   
4    0.714876  0.723140  0.731405  ...  0.161157  0.177686  0.173554   
..        ...       ...       ...  ...       ...       ...       ...   
395  0.636364  0.665289  0.698347  ...  0.396694  0.264463  0.099174   
396  0.512397  0.574380  0.628099  ...  0.334711  0.289256  0.285124   
397  0.669421  0.673554  0.702479  ...  0.148760  0.152893  0.161157   
398  0.400826  0.487603  0.549587  ...  0.392562  0.367769  0.409091   
399  0.615702  0.661157  0.615702  ...  0.264463  0.293388  0.301653   

         4090      4091      4092      4093      4094      4095  target  
0    0.475207  0.132231  0.148760  0.152893  0.161157  0.157025       0  
1    0.152893  0.152893  0.152893  0.152893  0.152893  0.152893       0  
2    0.128099  0.148760  0.144628  0.140496  0.148760  0.152893       0  
3    0.727273  0.743802  0.764463  0.752066  0.752066  0.739669       0  
4    0.177686  0.177686  0.177686  0.177686  0.173554  0.173554       0  
..        ...       ...       ...       ...       ...       ...     ...  
395  0.181818  0.243802  0.247934  0.161157  0.157025  0.136364      39  
396  0.338843  0.404959  0.458678  0.487603  0.512397  0.549587      39  
397  0.161157  0.173554  0.157025  0.177686  0.148760  0.190083      39  
398  0.479339  0.524793  0.545455  0.574380  0.590909  0.603306      39  
399  0.293388  0.322314  0.322314  0.359504  0.355372  0.384298      39  

[400 rows x 4097 columns]

In [27]:
X = faces_df.drop("target",axis=1)
Y = faces_df["target"]

import numpy as np

np.random.seed(42)

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2)

from sklearn.svm import SVC
model = SVC().fit(X_train,Y_train)
model.score(X_test,Y_test)

0.925

In [28]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier().fit(X_train,Y_train)
model.score(X_test,Y_test)

0.9125

In [29]:
Y_preds = np.array(model.predict(X_test))
np.mean(Y_preds==Y_test)

0.9125

In [30]:
model.predict_proba(X_test[:5])

array([[0.  , 0.01, 0.03, 0.03, 0.  , 0.  , 0.  , 0.  , 0.  , 0.03, 0.  ,
        0.03, 0.01, 0.02, 0.01, 0.01, 0.02, 0.  , 0.  , 0.01, 0.59, 0.  ,
        0.  , 0.  , 0.01, 0.  , 0.  , 0.  , 0.04, 0.03, 0.02, 0.01, 0.02,
        0.  , 0.05, 0.  , 0.01, 0.  , 0.01, 0.  ],
       [0.  , 0.01, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.01, 0.01, 0.  , 0.  , 0.  , 0.  , 0.03, 0.03,
        0.  , 0.02, 0.  , 0.01, 0.  , 0.  , 0.65, 0.02, 0.04, 0.  , 0.12,
        0.01, 0.  , 0.01, 0.  , 0.  , 0.03, 0.  ],
       [0.03, 0.02, 0.03, 0.42, 0.01, 0.02, 0.01, 0.01, 0.01, 0.05, 0.  ,
        0.01, 0.09, 0.01, 0.  , 0.01, 0.  , 0.05, 0.  , 0.  , 0.  , 0.  ,
        0.05, 0.  , 0.03, 0.01, 0.  , 0.02, 0.01, 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.01, 0.01, 0.  , 0.03, 0.  , 0.05],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.01, 0.  , 0.  , 0.  , 0.  , 0.  , 0.7 ,
        0.  , 0.01, 0.01, 0.01, 0

In [31]:
from sklearn.model_selection import cross_val_score

cv_score = cross_val_score(model,X,Y,cv=5)

In [32]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor

model.score(X_test,Y_test)


0.9125

In [33]:
np.mean(cv_score)

0.9400000000000001

In [34]:
probs = model.predict_proba(X_test)
probs[10:], len(probs)

(array([[0.27, 0.  , 0.01, ..., 0.11, 0.01, 0.01],
        [0.01, 0.02, 0.  , ..., 0.  , 0.  , 0.  ],
        [0.03, 0.  , 0.  , ..., 0.  , 0.  , 0.01],
        ...,
        [0.01, 0.04, 0.1 , ..., 0.01, 0.01, 0.01],
        [0.05, 0.01, 0.04, ..., 0.02, 0.  , 0.  ],
        [0.  , 0.01, 0.  , ..., 0.  , 0.07, 0.01]]),
 80)

In [35]:
prob_positive = probs[:,1]
prob_positive[:10]

array([0.01, 0.01, 0.02, 0.  , 0.01, 0.03, 0.  , 0.  , 0.01, 0.03])

In [37]:
from sklearn.metrics import roc_curve
fpr, tpr, thresholds = roc_curve(Y_test, prob_positive)

ValueError: multiclass format is not supported